### ISSUE TITLE
请问多个websocket服务是怎么处理身份认证和消息推送的，可有解决方案

### ISSUE THREAD

**Issue by acaiafan** [naah69/SpringCloud-Gateway-WebSocket-Demo#2]

**Comment by naah69** [comment]
需要自己定义接口进行身份认证，消息推送分为订阅模式和单点推送模式

**Comment by acaiafan** [comment]
> 需要自己定义接口进行身份认证，消息推送分为订阅模式和单点推送模式

部署多个websocket service，多个websocket连接建立在不同的server上，需要推送单点消息时，是如何确定由哪个service去推送呢，springcloud gateway 是否有提供什么解决方案

**Comment by naah69** [comment]
需要建立共享内存区，比如redis， 将所有websocket的sessionId存起来，使用mq沟通

**Comment by acaiafan** [comment]
> 需要建立共享内存区，比如redis， 将所有websocket的sessionId存起来，使用mq沟通

多谢，目前也是打算使用这种方案，gateway对websocket的支持还是有限，好像也并不支持根据服务名去寻址建立连接

**Comment by naah69** [comment]
是的 这个并不好做，因为前段传来的就直接是流了估计可能要根据url过滤可以实现
